/* jshint node: true */
/* jslint browser: true */
/* jslint asi: true */
'use strict'

/** A "turtle" generating a continuous set of vertices */
module.exports = Turtle

/** Seup up an instance.
 * (initX, initY) is the initial turtle position,
 * initAngle its initial orientation (in radians) */
function Turtle (initX, initY, initAngle) {
  this.x = initX
  this.y = initY
  this.direction = initAngle
  this.vertices = []
  this.vertices.push({x: this.x, y: this.y})
}

/** Rotate the turtle by "angle" radians */
Turtle.prototype.turn = function (angle) {
  this.direction += angle
}

/** Draw a line of length "length" from the current turtle position,
 * in its current direction. Position is upgraded accordingly. */
Turtle.prototype.drawLine = function (length) {
  this.x = this.x + length * Math.cos(this.direction)
  this.y = this.y + length * Math.sin(this.direction)
  this.vertices.push({x: this.x, y: this.y})
}

/** Return the set of vertices generated by previous calls
 * as an array of objects with "x" and "y" properties */
Turtle.prototype.getVertices = function () {
  return this.vertices
}
